// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    IconCarbonFaceActivatedFilled: typeof import('~icons/carbon/face-activated-filled')['default']
    IconCarbonFaceCool: typeof import('~icons/carbon/face-cool')['default']
    IconCarbonFaceDizzy: typeof import('~icons/carbon/face-dizzy')['default']
    IconCarbonFacePending: typeof import('~icons/carbon/face-pending')['default']
    IconCarbonLanguage: typeof import('~icons/carbon/language')['default']
    IconCarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCarbonWarning: typeof import('~icons/carbon/warning')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
